- id: dart-import-sorter
  name: Dart Import Sorter
  description: Automatically organize Dart imports
  language: system
  entry: dart run tidy_imports
  files: \.dart$
  pass_filenames: false

- id: flutter-import-sorter
  name: Flutter Import Sorter
  description: Automatically organize Dart imports in Flutter projects
  language: system
  entry: flutter pub run tidy_imports
  files: \.dart$
  pass_filenames: false
