name: tidy_imports
description: >-
  Automatically organize your Dart imports. Sorts and groups dart, flutter,
  package, and project imports alphabetically. Spiritual successor to import_sorter.
version: 1.1.0
repository: https://github.com/Franklyn-R-Silva/tidy_imports
homepage: https://github.com/Franklyn-R-Silva/tidy_imports
topics:
  - imports
  - formatter
  - cli
  - import-sorter
  - developer-tools

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  tidy_imports:

dependencies:
  args: ^2.5.0
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0

tidy_imports:
  emojis: false
